#!/bin/bash

FILENAME="$(cat info.json | jq -r ".name")_$(cat info.json | jq -r ".version")"
mkdir "../$FILENAME"
rsync -a --exclude 'buildmod' * "../$FILENAME/"
7z a -sdel "../$FILENAME.zip" "../$FILENAME"
mv "../$FILENAME.zip" ~/.factorio/mods/
