require("prototypes.item.items")
require("prototypes.item.ammo")
require("prototypes.entity.entities")
require("prototypes.entity.projectiles")
require("prototypes.recipe.recipes")
require("prototypes.technology.technologies")
require("prototypes.categories.fuel-category")
require("prototypes.categories.recipe-category")
