require("prototypes.item.items")
require('prototypes.entity.remnants')
require("prototypes.entity.entities")
require("prototypes.entity.projectiles")
require("prototypes.recipe.recipes")
require("prototypes.technology.technology")
require("prototypes.categories.fuel-category")

-- TODO: better advanced reprocessing process (used-up fuel + acid [in chemical plant] = components)
-- TODO: Support for Schall Artillery (https://mods.factorio.com/mod/SchallArtillery)
