require("prototypes.item.items")
require('prototypes.entity.remnants')
require("prototypes.entity.entities")
require("prototypes.entity.projectiles")
require("prototypes.recipe.recipes")
require("prototypes.technology.technology")
require("prototypes.categories.fuel-category")
require("prototypes.categories.recipe-category")

-- TODO: add remnants (MOX reactor)
-- TODO: Support for SChall Artillery (https://mods.factorio.com/mod/SchallArtillery)
